pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Restart Frontend') {
            steps {
                sh 'pm2 restart express-frontend || pm2 start frontend/server.js --name express-frontend'
            }
        }
    }
}
